# Generated by Django 5.2.7 on 2025-11-16 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_image_url_alter_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
    ]
